server:
  http_listen_port: 3100
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push
scrape_configs:
  - job_name: fastapi-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi
          host: localhost
