global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      # - targets: ['http:8000']  # Replace with your app's host and port
      -targets: ['http://localhost:8000'] # Replace with your app's
